CREATE TABLE IF NOT EXISTS servers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rs_id VARCHAR(64) UNIQUE NOT NULL,
  family ENUM('BASIC','CORE','ULTRA','TITAN','VELOCITY') NOT NULL,
  location VARCHAR(128) NOT NULL,
  cpu VARCHAR(255) NOT NULL,
  ram VARCHAR(64) NOT NULL,
  storage VARCHAR(255) NOT NULL,
  bandwidth VARCHAR(64) NOT NULL,
  base_price DECIMAL(10,2) NOT NULL,
  cnx_price DECIMAL(10,2) NOT NULL,
  coupon VARCHAR(64) NULL,
  qty INT DEFAULT 1,
  raw_json MEDIUMTEXT,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
